# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14HtB7_HzQ4gAeQZVbBf84Q1QBA5Cj-X_
"""

import streamlit as st
import random

st.title('Test Streamkit')
st.write('Hello World')

if st.button('Generate Random Number'):
  random_number = random.randint(1,100)
  st.write(f'Random Number: {random_number}')
